@ECHO OFF

SETX VENDOR1_USERNAME "user123"
SETX VENDOR1_PASSWORD "pw1234"
SETX VENDOR2_USERNAME "userabc"
SETX VENDOR2_PASSWORD "pwabcd"
SETX VENDOR3_USERNAME "pabc123"
SETX VENDOR3_PASSWORD "uabc123"
